num_of_features: 3 
num_of_classes: 14
encoder_type: 'resnet'
base_data_filepath:  "C:\\Users\\LENOVO\\Desktop\\supervised\\all_data\\Oct-29-2024\\hhar_watch_sr_50.joblib"
model_save_path: "C:\\Users\\LENOVO\\Desktop\\supervised"
data_augmentation: False
learning_rate: 1e-3
weight_decay: 1e-5
batch_size: 250
gpu_device: 1
num_of_epochs: 60
embedding_dim: 512
resnet_type: 'resnet_1_block_conv_5'